site_information:
  title: MakingMachinez
  description: 原付改造・プラレール改造
  domain: www.makingmachinez.com
  root_url: https://www.makingmachinez.com
  author:
    name: funnythingz. All rights reserved.
gentsuki:
  title: 原付改造カスタムブログ
  description: ライブディオ/ライブディオZX/スーパーディオを改造カスタムする日々の記録
plarail:
  title: プラレールのことを考えている
  description: プラレールを改造して、ミニ四駆のギヤボックスを搭載したり、爆速にしたりしています
