site_information:
  title: MakingMachinez
  description: 原付改造・プラレール改造
  domain: www.makingmachinez.com
  root_url: https://www.makingmachinez.com
  author:
    name: funnythingz. All rights reserved.
